apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: k8s-operator-dns-ops
  name: k8s-operator-dns-ops
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-operator-dns-ops
  namespace: k8s-operator-dns-ops
subjects:
- kind: ServiceAccount
  name: k8s-operator-dns-ops
  namespace: k8s-operator-dns-ops
roleRef:
  kind: ClusterRole 
  name: k8s-operator-dns-ops
  apiGroup: rbac.authorization.k8s.io
